# Generated by Django 4.2.1 on 2023-05-18 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=250)),
                ('website', models.URLField()),
                ('employer_logo', models.ImageField(default='employer_profile/company.png', upload_to='employer_profile')),
                ('about_us', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployerTerms2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=250, null=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('office_address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=250, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('terms2_date', models.DateTimeField()),
                ('attest', models.CharField(blank=True, max_length=250, null=True)),
                ('attest_paragraph', models.CharField(blank=True, max_length=250, null=True)),
                ('signature', models.CharField(blank=True, max_length=250, null=True)),
                ('agree2', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('role', models.CharField(max_length=250)),
                ('requirement', models.CharField(max_length=250)),
                ('probabtion', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('additional_skills', models.CharField(max_length=250)),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('job_dat', models.DateField(auto_now_add=True)),
                ('job_updated', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('employer_terms', models.TextField()),
                ('job_description', models.TextField()),
                ('employer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employer_profile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph1', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph2', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph3', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph4', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph5', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph6', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph7', models.CharField(blank=True, max_length=250, null=True)),
                ('signature', models.CharField(blank=True, max_length=250, null=True)),
                ('terms1_date', models.DateTimeField()),
                ('agree1', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
