# Generated by Django 4.2.1 on 2023-05-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerterms2',
            options={'managed': True, 'verbose_name': 'EmployerTerms2', 'verbose_name_plural': 'EmployerTerms2'},
        ),
        migrations.AddField(
            model_name='employerterms2',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='employerterms2',
            table='employerterms2',
        ),
    ]
