# Generated by Django 4.2.1 on 2023-05-18 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_alter_employerterms2_options_employerterms2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerterms2',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
