# Generated by Django 4.2.1 on 2023-05-19 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0005_alter_employerterm_user_alter_employerterms2_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('registration_no', models.CharField(blank=True, max_length=250, null=True)),
                ('pay_code', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EmployerPayment',
                'verbose_name_plural': 'EmployerPayment',
                'db_table': 'employerpayment',
                'managed': True,
            },
        ),
    ]
