# Generated by Django 4.2.1 on 2023-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_remove_employer_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
