# Generated by Django 4.2.1 on 2023-05-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_job_post_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='new',
            new_name='job_open',
        ),
    ]
