# Generated by Django 4.2.1 on 2023-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_alter_employer_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='employer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
