# Generated by Django 4.2.1 on 2023-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0018_alter_employer_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='num',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
