# Generated by Django 4.2.1 on 2023-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0020_alter_job_post_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='num_alpha',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
