# Generated by Django 4.2.1 on 2023-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0022_alter_job_post_num_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
