# Generated by Django 4.2.1 on 2023-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0026_alter_job_post_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='deadline',
            field=models.CharField(max_length=250),
        ),
    ]
