# Generated by Django 4.2.1 on 2023-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0029_alter_job_post_job_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='employ_logo',
            field=models.ImageField(default='employer_profile/company.png', upload_to='employer_profile'),
        ),
    ]
