# Generated by Django 4.2.1 on 2023-05-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_cat_slug'),
        ('employers', '0032_alter_job_post_employ_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
