# Generated by Django 4.2.1 on 2023-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0034_alter_job_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='job_dat',
        ),
        migrations.RemoveField(
            model_name='job_post',
            name='job_date',
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
