# Generated by Django 4.2.1 on 2023-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0037_alter_job_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
