# Generated by Django 4.2.1 on 2023-05-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0038_alter_job_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_closed',
            field=models.BooleanField(default=False),
        ),
    ]
