# Generated by Django 4.2.1 on 2023-05-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0039_alter_job_post_job_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerpayment',
            name='registration_no',
        ),
    ]
