# Generated by Django 4.2.1 on 2023-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0040_remove_employerpayment_registration_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerpayment',
            options={'managed': True, 'verbose_name': 'EmployerPayment', 'verbose_name_plural': 'EmployerPayments'},
        ),
        migrations.AlterModelOptions(
            name='job_post',
            options={'managed': True, 'verbose_name': 'Job_Post', 'verbose_name_plural': 'Job_Posts'},
        ),
        migrations.RemoveField(
            model_name='employerterm',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='employerterms2',
            name='signature',
        ),
        migrations.AddField(
            model_name='employer_profile',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='job_post',
            table='job_post',
        ),
    ]
