# Generated by Django 4.2.1 on 2023-05-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0041_alter_employerpayment_options_alter_job_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerterm',
            options={'managed': True, 'verbose_name': 'EmployerTerm', 'verbose_name_plural': 'EmployerTerms'},
        ),
        migrations.AlterModelTable(
            name='employerterm',
            table='employerterm',
        ),
    ]
