# Generated by Django 4.2.1 on 2023-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0043_alter_employerpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpayment',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employerpayment',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
