# Generated by Django 4.2.1 on 2023-06-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0044_employerpayment_first_name_employerpayment_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpayment',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employerpayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
