# Generated by Django 4.2.1 on 2023-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0046_remove_employerterms2_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerterms2',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employerterms2',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
