# Generated by Django 4.2.1 on 2023-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0047_alter_employerterms2_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
