# Generated by Django 4.2.1 on 2023-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0052_alter_job_post_job_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
