# Generated by Django 4.2.1 on 2023-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_year', models.CharField(max_length=4)),
                ('crafted_by', models.CharField(default='', max_length=250)),
                ('crafted_by_whatsapp', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('crafted_by_website', models.URLField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'CreatedBy',
                'verbose_name_plural': 'CreatedBys',
                'db_table': 'createdby',
                'managed': True,
            },
        ),
    ]
