# Generated by Django 4.2.1 on 2023-05-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createdby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdby',
            name='copyright_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
