# Generated by Django 4.2.1 on 2023-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor_form2',
            name='dated_this_day',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guarantor_form2',
            name='witnesed_date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
