# Generated by Django 4.2.1 on 2023-05-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_guarantor_form2_dated_this_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('role', models.CharField(max_length=250)),
                ('requirement', models.CharField(max_length=250)),
                ('probabtion', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('additional_skills', models.CharField(max_length=250)),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('job_dat', models.DateField(auto_now_add=True)),
                ('job_updated', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('employer_terms', models.TextField()),
                ('job_description', models.TextField()),
                ('salary_expected', models.CharField(max_length=50)),
                ('about_yourself', models.TextField()),
                ('hired', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('resigned', models.BooleanField(default=False)),
                ('general_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.general_information')),
            ],
        ),
    ]
