# Generated by Django 4.2.1 on 2023-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_job_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='applied',
            field=models.BooleanField(default=True),
        ),
    ]
