# Generated by Django 4.2.1 on 2023-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_job_apply_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
