# Generated by Django 4.2.1 on 2023-05-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_employer_profile_slug'),
        ('applicants', '0005_alter_job_apply_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.job_post'),
        ),
    ]
