# Generated by Django 4.2.1 on 2023-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_job_apply_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
