# Generated by Django 4.2.1 on 2023-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_job_apply_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='notice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job_apply',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
