# Generated by Django 4.2.1 on 2023-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_job_apply_notice_job_apply_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='new_applied',
            field=models.BooleanField(default=True),
        ),
    ]
