# Generated by Django 4.2.1 on 2023-05-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0029_alter_job_post_job_open'),
        ('applicants', '0010_job_apply_notice_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employer_profile'),
        ),
    ]
