# Generated by Django 4.2.1 on 2023-05-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_job_apply_job_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_apply',
            old_name='job_post',
            new_name='employer_profile',
        ),
    ]
