# Generated by Django 4.2.1 on 2023-05-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0030_job_post_employ_logo'),
        ('applicants', '0012_rename_job_post_job_apply_employer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply',
            name='employer_profile',
        ),
        migrations.AddField(
            model_name='job_apply',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.job_post'),
        ),
    ]
