# Generated by Django 4.2.1 on 2023-05-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_job_apply_empl_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
