# Generated by Django 4.2.1 on 2023-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_job_apply_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='employer',
            field=models.CharField(default='', max_length=250),
        ),
    ]
