# Generated by Django 4.2.1 on 2023-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0016_job_apply_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='employer',
            field=models.CharField(max_length=250),
        ),
    ]
