# Generated by Django 4.2.1 on 2023-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_general_information_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='qualification',
            field=models.CharField(max_length=250),
        ),
    ]
