# Generated by Django 4.2.1 on 2023-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_job_apply_terminated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply',
            name='notice_read',
        ),
        migrations.AddField(
            model_name='job_apply',
            name='applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_apply',
            name='hireded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_apply',
            name='resigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_apply',
            name='shortlisted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_apply',
            name='terminated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
