# Generated by Django 4.2.1 on 2023-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0023_remove_job_apply_notice_read_job_apply_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='declined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
