# Generated by Django 4.2.1 on 2023-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0024_job_apply_declined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='category',
            field=models.CharField(default='health worker', max_length=250),
        ),
    ]
