# Generated by Django 4.2.1 on 2023-05-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0026_alter_job_apply_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_apply',
            old_name='category',
            new_name='category_apply',
        ),
    ]
