# Generated by Django 4.2.1 on 2023-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0028_applicantpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantpayment',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
