# Generated by Django 4.2.1 on 2023-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0030_alter_job_apply_options_alter_job_apply_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpayment',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
