# Generated by Django 4.2.1 on 2023-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0032_alter_applicantpayment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='new_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
