# Generated by Django 4.2.1 on 2023-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0033_alter_job_apply_applied_alter_job_apply_new_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='applied',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='new_applied',
            field=models.BooleanField(),
        ),
    ]
