# Generated by Django 4.2.1 on 2023-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0035_alter_job_apply_applied_alter_job_apply_new_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply',
            name='deadline',
        ),
        migrations.AddField(
            model_name='job_apply',
            name='deadline_date',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='employer_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='language_spoken',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='previous_company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='salary_expected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
