# Generated by Django 4.2.1 on 2023-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0036_remove_job_apply_deadline_job_apply_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
