# Generated by Django 4.2.1 on 2023-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0038_alter_job_apply_category_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='admin_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
