# Generated by Django 4.2.1 on 2023-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('favicon', models.ImageField(blank=True, default='logo/favicon-96x96.png', null=True, upload_to='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('head_office', models.CharField(max_length=100)),
                ('branch_office1', models.CharField(max_length=100)),
                ('branch_office2', models.CharField(max_length=100)),
                ('mobile1', models.CharField(max_length=20)),
                ('mobile2', models.CharField(max_length=20)),
                ('mobile3', models.CharField(max_length=20)),
                ('mobile4', models.CharField(max_length=20)),
                ('mobile5', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('about2', models.TextField(blank=True, null=True)),
                ('about_img', models.ImageField(blank=True, default='logo/aboutus.jpg', null=True, upload_to='logo')),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfile',
                'db_table': 'companyprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cleared', models.DateTimeField(auto_now=True)),
                ('admin_note', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Cleared', 'Cleared')], default='New', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Featured_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_img', models.ImageField(blank=True, default='company/company.png', null=True, upload_to='company')),
            ],
            options={
                'verbose_name': 'Featured_company',
                'verbose_name_plural': 'Featured_companies',
                'db_table': 'featured_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registration_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(max_length=50)),
                ('applicant_fee', models.IntegerField()),
                ('employer_fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Registration_Fee',
                'verbose_name_plural': 'Registration_Fees',
                'db_table': 'registration_fee',
                'managed': True,
            },
        ),
    ]
