# Generated by Django 4.2.1 on 2023-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_companyprofile_branch_office1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_fee',
            name='large_company',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='registration_fee',
            name='worker_year_fee',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
