# Generated by Django 4.2.1 on 2023-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registration_fee_large_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_fee',
            name='large_company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration_fee',
            name='worker_year_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
