# Generated by Django 4.2.1 on 2023-06-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('job_image', models.ImageField(blank=True, default='jobs/job.jpg', null=True, upload_to='jobs')),
                ('job_description', models.TextField()),
                ('job_description2', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'verbose_name': 'JobTitle',
                'verbose_name_plural': 'JobTitles',
                'db_table': 'jobtitle',
                'managed': True,
            },
        ),
    ]
