# Generated by Django 4.2.1 on 2023-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_jobtitle_list_item5_jobtitle_list_item6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
