# Generated by Django 4.2.1 on 2023-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_jobtitle_list2_item1_jobtitle_list2_item2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='list_item8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
