# Generated by Django 4.2.1 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_jobtitle_list_item8'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='list_item10',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='list_item9',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
