# Generated by Django 4.2.1 on 2023-06-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_jobtitle_list_item10_jobtitle_list_item9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='job_description2',
        ),
    ]
