# Generated by Django 4.2.1 on 2023-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_jobtitle_list2_item8'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='job_image2',
            field=models.ImageField(blank=True, default='jobs/job.jpg', null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_image3',
            field=models.ImageField(blank=True, default='jobs/job.jpg', null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_image4',
            field=models.ImageField(blank=True, default='jobs/job.jpg', null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_image5',
            field=models.ImageField(blank=True, default='jobs/job.jpg', null=True, upload_to='jobs'),
        ),
    ]
