# Generated by Django 4.2.1 on 2023-06-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_jobtitle_job_image2_jobtitle_job_image3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTitle',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
