# Generated by Django 4.2.1 on 2023-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_jobtitle_service_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='job_image2',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_image3',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_image4',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='job_image5',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
    ]
