# Generated by Django 4.2.1 on 2023-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_service_job_image2_alter_service_job_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
